name: FastAPI-example
services:
  postgres:
    image: postgres:16 
    container_name: example-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
