"""doctor_migration

Revision ID: 0e35895be866
Revises: f87a16e1d361
Create Date: 2025-02-26 05:12:34.663601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e35895be866'
down_revision: Union[str, None] = 'f87a16e1d361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('crm', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm')
    )
    # ### end Alembic commands ###
    
    # Inserindo médicos na tabela doctors
    op.execute("""
        INSERT INTO doctors (name, specialty, crm) VALUES
        ('Dr. Carlos Mendes', 'Clínico Geral', '123456-SP'),
        ('Dra. Juliana Oliveira', 'Cardiologia', '654321-RJ'),
        ('Dr. Roberto Souza', 'Ortopedia', '789012-MG')
    """)


def downgrade() -> None:
    # Removendo os médicos inseridos
    op.execute("""
        DELETE FROM doctors WHERE crm IN ('123456-SP', '654321-RJ', '789012-MG')
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###