"""scheduling_migration

Revision ID: 64f70068a9a6
Revises: 0e35895be866
Create Date: 2025-02-26 05:54:03.654498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f70068a9a6'
down_revision: Union[str, None] = '0e35895be866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduling_date', sa.String(), nullable=False),
    sa.Column('scheduling_time', sa.String(), nullable=False),
    sa.Column('scheduling_type', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('rescheduled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedulings')
    # ### end Alembic commands ###
