"""patient_migration

Revision ID: f87a16e1d361
Revises: 9541188de65f
Create Date: 2025-02-26 04:48:34.644505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87a16e1d361'
down_revision: Union[str, None] = '9541188de65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('cpf', sa.String(), nullable=False),
        sa.Column('birth_date', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('health_insurance', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf')
    )
    # Inserindo o paciente
    patients_table = sa.table('patients',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('cpf', sa.String),
        sa.column('birth_date', sa.String),
        sa.column('phone', sa.String),
        sa.column('health_insurance', sa.Boolean)
    )
    op.bulk_insert(
        patients_table,
        [
            {
                "id": 1,
                "name": "Guilherme Alencar",
                "cpf": "08348599479",
                "birth_date": "17/09/2002",
                "phone": "82996340393",
                "health_insurance": True,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
